name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - name: Install Packages
        run: npm install
      - name: Build
        run: |+
          npm run build
      - name: Lint
        run: |+
          npm run lint
      - name: Test
        run: |+
          npm run test
